baseURL = 'https://bugzy.dev/'
languageCode = 'en-gb'
title = 'Bugzy'

[params]
  fullWidthTheme = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
[[module.imports]]
  path = 'github.com/panr/hugo-theme-terminal/v4'

[languages]
  [languages.en.params.logo]
    logoText = "Bugzy"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

